---
- hosts: all
  remote_user: vagrant
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https',
              'ca-certificates',
              'curl',
              'software-properties-common',
              'python-pip',
              'virtualenv',
              'python-setuptools',
              'openjdk-8-jdk']

    - name: Add Jenkins repository key
      apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins.io.key"
        state: present

    - name: Clean apt lists
      file:
        path: "/var/lib/apt/lists/*"
        state: absent

    - name: Update apt following apt mergelists fix
      apt: update_cache=yes

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Install Jenkins
      apt: name=jenkins update_cache=yes cache_valid_time=3600

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Add users to docker group.
      shell: "usermod -aG docker {{ item }}"
      with_items:
        - vagrant
        - jenkins